SEED_TASKS = [
    {"name": "Сбор требований", "description": "Интервью с заказчиком, фиксация ТЗ",
     "assignee": "Ирина", "duration": 3, "predecessors": []},
    {"name": "Дизайн интерфейса", "description": "Прототипы экранов в Figma",
     "assignee": "Павел", "duration": 5, "predecessors": ["Сбор требований"]},
    {"name": "Проектирование БД", "description": "Схема таблиц, миграции",
     "assignee": "Алексей", "duration": 4, "predecessors": ["Сбор требований"]},
    {"name": "Backend: API задач", "description": "CRUD эндпоинты, валидация",
     "assignee": "Алексей", "duration": 6, "predecessors": ["Проектирование БД"]},
    {"name": "Frontend: диаграмма Гантта", "description": "Компонент визуализации плана",
     "assignee": "Мария", "duration": 7, "predecessors": ["Дизайн интерфейса"]},
    {"name": "Интеграция LLM-чата", "description": "Подключение MCP + модели",
     "assignee": "Алексей", "duration": 5, "predecessors": ["Backend: API задач"]},
    {"name": "Тестирование", "description": "Функциональные и регрессионные тесты",
     "assignee": "Ирина", "duration": 4,
     "predecessors": ["Frontend: диаграмма Гантта", "Интеграция LLM-чата"]},
    {"name": "Деплой", "description": "Выкладка на прод, финальная проверка",
     "assignee": "Павел", "duration": 2, "predecessors": ["Тестирование"]},
]
